#ad_manager_publisher_homepage:
#    pattern:  /admin/publishers
#    defaults: { _controller: AdManagerPublisherBundle:Publisher:index }
#
#
#publisher_show:
#    pattern:  /admin/publisher/show/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Publisher:show }
#
#add_publisher:
#    pattern:  /admin/publisher/add
#    defaults: { _controller: AdManagerPublisherBundle:Publisher:add }
#    
#publisher_delete:
#    pattern:  /admin/publisher/delete/{id}/{confirm}
#    defaults: { _controller: AdManagerPublisherBundle:Publisher:delete, confirm : 0}
#
#publisher_edit:
#    pattern:  /admin/publisher/edit/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Publisher:edit}
#    
#    
#ad_manager_ad_homepage:
#    pattern:  /admin/ads
#    defaults: { _controller: AdManagerPublisherBundle:Ad:index }
#
#ad_show:
#    pattern:  /admin/ad/show/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Ad:show }
#    
#add_ad:
#    pattern:  /admin/ad/add
#    defaults: { _controller: AdManagerPublisherBundle:Ad:add }
#  
#ad_delete:
#    pattern:  /admin/ad/delete/{id}/{confirm}
#    defaults: { _controller: AdManagerPublisherBundle:Ad:delete, confirm : 0 }
#  
#ad_edit:
#    pattern:  /admin/ad/edit/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Ad:edit }
#  
#ad_manager_field_homepage:
#    pattern:  /admin/fields
#    defaults: { _controller: AdManagerPublisherBundle:Field:index }
#field_show:
#    pattern:  /admin/field/show/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Field:show }
#    
#add_field:
#    pattern:  /admin/field/add
#    defaults: { _controller: AdManagerPublisherBundle:Field:add }
#  
#field_delete:
#    pattern:  /admin/field/delete/{id}/{confirm}
#    defaults: { _controller: AdManagerPublisherBundle:Field:delete, confirm : 0 }
#  
#field_edit:
#    pattern:  /admin/field/edit/{id}
#    defaults: { _controller: AdManagerPublisherBundle:Field:edit}
#  
#  