<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Iphp\ContentBundle\Entity;

use Iphp\ContentBundle\Entity\BaseContent as BaseContent;

use Doctrine\ORM\Mapping as ORM;
/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
/**
* @ORM\Entity
* @ORM\Table(name="content")
*/
class Content extends BaseContent
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    public function __toString()
    {
        if (empty($this->title))
            return 'Добавить новый';
        return $this->getTitle();
    }
    
    /**
     * Get title
     *
     * @return string $title
     */
//    public function getTitle()
//    {
//        if (empty($this->title))
//            return 'Please enter content title';
//        return $this->title;
//    }
}